2016-10-07 21:52:34.827 [error] <0.459.0> riak_sysmon_filter:get_node_map: error badarg @ [{ets,match_object,[sys_dist,'_'],[]},{ets,tab2list,1,[{file,"ets.erl"},{line,710}]},{riak_sysmon_filter,get_node_map,0,[{file,"/Users/cmeiklejohn/Documents/antidote/_build/default/lib/riak_sysmon/src/riak_sysmon_filter.erl"},{line,378}]},{riak_sysmon_filter,init,1,[{file,"/Users/cmeiklejohn/Documents/antidote/_build/default/lib/riak_sysmon/src/riak_sysmon_filter.erl"},{line,155}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]
2016-10-07 21:52:35.244 [critical] <0.521.0>@riak_core_ring_manager:reload_ring:355 Failed to load ring file: "no such file or directory"
2016-10-07 21:52:35.258 [error] <0.521.0> CRASH REPORT Process riak_core_ring_manager with 0 neighbours exited with reason: bad return value: {error,enoent} in gen_server:init_it/6 line 356
2016-10-07 21:52:35.258 [error] <0.507.0> Supervisor riak_core_sup had child riak_core_ring_manager started with riak_core_ring_manager:start_link() at undefined exit with reason bad return value: {error,enoent} in context start_error
2016-10-07 21:52:35.259 [error] <0.505.0> CRASH REPORT Process <0.505.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,riak_core_ring_manager,{bad_return_value,{error,enoent}}}},{riak_core_app,start,[normal,[]]}} in application_master:init/4 line 134
